// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortHub.Api.Data;

#nullable disable

namespace PortHub.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251107123455_RelacionSlotYAirline")]
    partial class RelacionSlotYAirline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortHub.Api.Models.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApiUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaseAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique();

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Airlines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApiKey = "AR_KEY_123456789ABCDEF01234",
                            ApiUrl = "http://localhost:5241/api/airline",
                            BaseAddress = "Buenos Aires",
                            Code = "AR",
                            Country = "Argentina",
                            Name = "Aerolíneas Argentinas"
                        });
                });

            modelBuilder.Entity("PortHub.Api.Models.Boarding", b =>
                {
                    b.Property<int>("BoardingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoardingId"));

                    b.Property<DateTime>("BoardingTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GateId")
                        .HasColumnType("int");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BoardingId");

                    b.HasIndex("GateId");

                    b.HasIndex("SlotId");

                    b.HasIndex("TicketNumber", "SlotId")
                        .IsUnique()
                        .HasDatabaseName("IX_Boardings_TicketId_SlotId");

                    b.ToTable("Boardings");
                });

            modelBuilder.Entity("PortHub.Api.Models.Gate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Gates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true,
                            Location = "Terminal A - Norte",
                            Name = "A1"
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = true,
                            Location = "Terminal A - Norte",
                            Name = "A2"
                        },
                        new
                        {
                            Id = 3,
                            IsAvailable = true,
                            Location = "Terminal B - Sur",
                            Name = "B1"
                        },
                        new
                        {
                            Id = 4,
                            IsAvailable = true,
                            Location = "Terminal B - Sur",
                            Name = "B2"
                        },
                        new
                        {
                            Id = 5,
                            IsAvailable = true,
                            Location = "Terminal C - Internacional",
                            Name = "C1"
                        });
                });

            modelBuilder.Entity("PortHub.Api.Models.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AirlineId")
                        .HasColumnType("int");

                    b.Property<string>("FlightCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("GateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReservationExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Runway")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("ScheduleTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("GateId");

                    b.HasIndex("ScheduleTime", "Runway")
                        .IsUnique()
                        .HasDatabaseName("IX_Slots_ScheduleTime_Runway");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("PortHub.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PortHub.Api.Models.Boarding", b =>
                {
                    b.HasOne("PortHub.Api.Models.Gate", "Gate")
                        .WithMany()
                        .HasForeignKey("GateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortHub.Api.Models.Slot", "Slot")
                        .WithMany("Boardings")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gate");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("PortHub.Api.Models.Slot", b =>
                {
                    b.HasOne("PortHub.Api.Models.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId");

                    b.HasOne("PortHub.Api.Models.Gate", "Gate")
                        .WithMany("Slots")
                        .HasForeignKey("GateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Airline");

                    b.Navigation("Gate");
                });

            modelBuilder.Entity("PortHub.Api.Models.Gate", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("PortHub.Api.Models.Slot", b =>
                {
                    b.Navigation("Boardings");
                });
#pragma warning restore 612, 618
        }
    }
}
