// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortHub.Api.Data;

#nullable disable

namespace PortHub.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortHub.Api.Models.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BaseAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique();

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Airlines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApiKey = "AS_DEV_KEY_123456789ABCDEF",
                            ApiUrl = "https://localhost:7001/api",
                            BaseAddress = "Buenos Aires",
                            Code = "AS",
                            Country = "Argentina",
                            Name = "AeroSol"
                        });
                });

            modelBuilder.Entity("PortHub.Api.Models.Boarding", b =>
                {
                    b.Property<int>("BoardingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoardingId"));

                    b.Property<DateTime>("AccessTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<bool>("Validation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("BoardingId");

                    b.HasIndex("SlotId");

                    b.ToTable("Boardings", (string)null);
                });

            modelBuilder.Entity("PortHub.Api.Models.Gate", b =>
                {
                    b.Property<int>("GateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GateId"));

                    b.Property<bool>("Available")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("GateName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GateId");

                    b.HasIndex("GateName")
                        .IsUnique();

                    b.ToTable("Gates", (string)null);
                });

            modelBuilder.Entity("PortHub.Api.Models.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("GateId")
                        .HasColumnType("int");

                    b.Property<string>("Runway")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("GateId");

                    b.HasIndex("Runway", "ScheduledTime")
                        .IsUnique()
                        .HasDatabaseName("IX_Slot_Runway_ScheduledTime");

                    b.ToTable("Slots", (string)null);
                });

            modelBuilder.Entity("PortHub.Api.Models.Boarding", b =>
                {
                    b.HasOne("PortHub.Api.Models.Slot", "Slot")
                        .WithMany("Boardings")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("PortHub.Api.Models.Slot", b =>
                {
                    b.HasOne("PortHub.Api.Models.Airline", "Airline")
                        .WithMany("Slots")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortHub.Api.Models.Gate", "Gate")
                        .WithMany("Slots")
                        .HasForeignKey("GateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Airline");

                    b.Navigation("Gate");
                });

            modelBuilder.Entity("PortHub.Api.Models.Airline", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("PortHub.Api.Models.Gate", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("PortHub.Api.Models.Slot", b =>
                {
                    b.Navigation("Boardings");
                });
#pragma warning restore 612, 618
        }
    }
}
